######################################################################
# Automatically generated by qmake (3.0) Sun Nov 5 07:53:00 2017
######################################################################

TEMPLATE = app
TARGET = SimpleImageViewer
QT += core gui widgets
INCLUDEPATH += .

# Input
SOURCES += simpleimageviewer.cpp
