######################################################################
# Automatically generated by qmake (3.0) Sun Aug 20 13:32:29 2017
######################################################################

TEMPLATE = app
TARGET = phonebook
QT += core gui widgets sql
INCLUDEPATH += .

# Input
SOURCES += phonebook.cpp
